### ISSUE TITLE
feature request: scheduled PR preview in GitHub Actions

### ISSUE THREAD

**Issue by Oreoxmt** [Oreoxmt/pingcap-docsite-preview#32]
Introduce a more flexible and centralized scheduling mechanism in GitHub Actions, allowing workflows to be triggered on a schedule without the need to set a specific branch as the default.

Support centralized management of scheduled events across various branches. For example:
 
```
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
```

For more information, see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
